name: products CI CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: check out
        uses: actions/checkout@v2

      - name: Change working directory
        run: cd ProductApp
    
      - name: dotnet framework setup
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '5.0.x'
      
      - name: dotnet restore packages
        run: dotnet restore
        
      
      - name: dotnet build
        run: dotnet build -c Release --no-restore

    
  
  


    
